/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        bg: "var(--bg)",
        surface: "var(--surface)",
        raised: "var(--raised)",
        sunken: "var(--sunken)",
        line: "var(--line)",
        "line-strong": "var(--line-strong)",
        ink: "var(--ink)",
        "ink-2": "var(--ink-2)",
        "ink-3": "var(--ink-3)",
        accent: "var(--accent)",
        "accent-hover": "var(--accent-hover)",
        "accent-text": "var(--accent-text)",
        "accent-soft": "var(--accent-soft)",
        "accent-line": "var(--accent-line)",
        "on-accent": "var(--on-accent)",
        ok: "var(--ok)",
        warn: "var(--warn)",
        danger: "var(--danger)",
        "series-1": "var(--series-1)",
        "series-2": "var(--series-2)",
        "series-3": "var(--series-3)",
        "series-4": "var(--series-4)",
        "series-5": "var(--series-5)",
      },
      fontFamily: {
        sans: ["Geist", "ui-sans-serif", "system-ui", "-apple-system", "Segoe UI", "Roboto", "sans-serif"],
        mono: ["GeistMono", "ui-monospace", "SFMono-Regular", "Menlo", "monospace"],
      },
      maxWidth: { shell: "1220px", prose: "62ch" },
      borderRadius: { xl: "10px", "2xl": "14px", "3xl": "20px" },
      boxShadow: {
        card: "var(--shadow-card)",
        lift: "var(--shadow-lift)",
        glow: "var(--shadow-glow)",
      },
      transitionTimingFunction: { out: "cubic-bezier(.22,.61,.36,1)" },
      keyframes: {
        rise: { from: { opacity: "0", transform: "translateY(16px)" }, to: { opacity: "1", transform: "none" } },
        fade: { from: { opacity: "0" }, to: { opacity: "1" } },
        caret: { "0%,49%": { opacity: "1" }, "50%,100%": { opacity: "0" } },
        flow: { from: { strokeDashoffset: "24" }, to: { strokeDashoffset: "0" } },
        pulseDot: { "0%,100%": { opacity: ".3" }, "50%": { opacity: "1" } },
        sweep: { "0%": { transform: "translateX(-100%)" }, "100%": { transform: "translateX(200%)" } },
      },
      animation: {
        rise: "rise .6s cubic-bezier(.22,.61,.36,1) both",
        fade: "fade .5s ease-out both",
        caret: "caret 1.05s steps(1) infinite",
        flow: "flow 1.1s linear infinite",
        pulseDot: "pulseDot 2s ease-in-out infinite",
        sweep: "sweep 2.4s ease-in-out infinite",
      },
    },
  },
  plugins: [],
};
